
import { ArticlesSection } from '@/components/vision-forge/ArticlesSection';
import { getArticles } from '@/lib/articles';
import type { Metadata } from 'next';
import { Suspense } from 'react';
import { ArticlesSkeleton } from '@/components/vision-forge/ArticlesSkeleton';

export const metadata: Metadata = {
    title: 'Technology Articles | Imagen BrainAi',
    description: 'Explore the latest articles on AI, software, and other emerging technologies, generated by Imagen BrainAi.',
};

const technologyTopics = [
    'How AI Image Upscaling Technology Works Its Magic',
    'The Technical Difference Between Midjourney, DALL-E 3, and Stable Diffusion',
    'Understanding Latent Space: The AI\'s Creative Playground',
    'The Role of GPUs in Modern AI Image Generation',
];

async function ArticleList() {
    const articles = await getArticles('Technology', technologyTopics);
    return <ArticlesSection articles={articles} topics={technologyTopics} category="Technology" />;
}

export default function TechnologyPage() {
    return (
        <main className="py-12">
            <section className="container mx-auto px-4">
                <header className="text-center mb-12">
                    <h2 className="text-4xl font-extrabold tracking-tight text-foreground">
                        Technology Insights
                    </h2>
                    <p className="text-muted-foreground mt-2 max-w-3xl mx-auto">
                        Stay updated with the latest trends and breakthroughs in the world of technology, all generated by AI.
                    </p>
                </header>
                <Suspense fallback={<ArticlesSkeleton />}>
                    <ArticleList />
                </Suspense>
            </section>
        </main>
    );
}
