
import { ArticlesSection } from '@/components/vision-forge/ArticlesSection';
import { getArticles } from '@/lib/articles';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Technology Articles | Imagen BrainAi',
    description: 'Explore the latest articles on AI, software, and other emerging technologies, generated by Imagen BrainAi.',
};

const technologyTopics = [
    'The Future of Artificial Intelligence in Everyday Life',
    'Quantum Computing: A Beginner\'s Simple Guide to a Complex Topic',
    'How 5G Technology is Actively Revolutionizing the World Today',
    'The Rise of Cybersecurity in the Modern Digital Age',
];

export default async function TechnologyPage() {
    const articles = await getArticles('Technology', technologyTopics);
    return (
        <main className="py-12">
            <ArticlesSection
                articles={articles} 
                topics={technologyTopics} 
                category="Technology" 
                headline="Technology Insights"
                subheadline="Stay updated with the latest trends and breakthroughs in the world of technology, all generated by AI."
            />
        </main>
    );
}
