
import { ArticlesSection } from '@/components/vision-forge/ArticlesSection';
import { getArticles } from '@/lib/articles';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Prompts Articles | Imagen BrainAi',
    description: 'Master the art of prompt engineering with our guides and articles, generated by Imagen BrainAi.',
};

const promptsTopics = [
    'The Definitive Guide to Crafting Effective AI Art Prompts',
    'Using Negative Prompts to Refine Your AI Image Generation',
    'Advanced Prompting Techniques for Photorealistic AI Image Results',
    'How to Achieve Perfect Character Consistency Across Images',
];

export default async function PromptsPage() {
    const articles = await getArticles('Prompts', promptsTopics);
    return (
        <main className="py-12">
            <ArticlesSection 
                articles={articles}
                topics={promptsTopics} 
                category="Prompts" 
                headline="Mastering AI Prompts"
                subheadline="Learn how to write better prompts to unlock the full potential of AI image generation."
            />
        </main>
    );
}
