
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy | Imagen BrainAi',
  description: 'Read the Privacy Policy for Imagen BrainAi to understand how we collect, use, and protect your personal information.',
};

export default function PrivacyPolicyPage() {
  return (
    <main className="container mx-auto py-12 px-4">
      <header className="text-center mb-10">
        <h1 className="text-4xl font-extrabold tracking-tight text-foreground mb-3">
          Privacy Policy
        </h1>
        <p className="text-lg text-foreground/80">Last Updated: 2024-06-27</p>
      </header>

      <div className="max-w-3xl mx-auto space-y-6 text-base leading-relaxed">
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">1. Introduction</h2>
          <p className="text-foreground">
            Welcome to Imagen BrainAi ("we," "us," or "our"). We are committed to protecting your personal information and your right to privacy. If you have any questions or concerns about this privacy notice, or our practices with regards to your personal information, please contact us at privacy@imagenbrain.ai.
          </p>
          <p className="mt-2 text-foreground">
            This Privacy Policy governs the privacy policies and practices of our website, Imagen BrainAi (the "Website"). Please read this Privacy Policy carefully. We will alert you to any changes to this Policy by changing the "last updated" date at the top of this Policy. Any changes become effective immediately upon publication on our Website, and you waive specific notice of any changes to the Policy by continuing to use and access our Website.
          </p>
          <p className="font-bold mt-2 text-destructive">
            IMPORTANT: This is a template Privacy Policy and should be reviewed and customized by a legal professional to ensure it accurately reflects your data practices and complies with all applicable laws and regulations. Do not use this template as-is for your live website.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">2. Information We Collect</h2>
          <p className="text-foreground">
            We may collect information about you in a variety of ways. The information we may collect on the Website includes:
          </p>
          <ul className="list-disc list-inside pl-4 mt-2 space-y-1 text-foreground">
            <li>
              <strong>Personal Data:</strong> Personally identifiable information, such as your name, email address, and other contact details that you voluntarily give to us when you register with the Website or when you choose to participate in various activities related to the Website, such as online chat and message boards.
            </li>
            <li>
              <strong>Usage Data:</strong> Information our servers automatically collect when you access the Website, such as your IP address, your browser type, your operating system, your access times, and the pages you have viewed directly before and afer accessing the Website.
            </li>
            <li>
              <strong>Generated Content:</strong> Prompts you provide and images generated by our AI services. While we strive to ensure privacy, understand that this content passes through our systems.
            </li>
            <li>
              <strong>Cookies and Tracking Technologies:</strong> We may use cookies, web beacons, tracking pixels, and other tracking technologies on the Website to help customize the Website and improve your experience.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">3. How We Use Your Information</h2>
          <p className="text-foreground">
            Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Website to:
          </p>
          <ul className="list-disc list-inside pl-4 mt-2 space-y-1 text-foreground">
            <li>Create and manage your account.</li>
            <li>Provide and improve our AI image generation services.</li>
            <li>Email you regarding your account or order.</li>
            <li>Enable user-to-user communications.</li>
            <li>Monitor and analyze usage and trends to improve your experience with the Website.</li>
            <li>Notify you of updates to the Website.</li>
            <li>Offer new products, services, and/or recommendations to you.</li>
            <li>Prevent fraudulent transactions, monitor against theft, and protect against criminal activity.</li>
            <li>Request feedback and contact you about your use of the Website.</li>
            <li>Resolve disputes and troubleshoot problems.</li>
            <li>Respond to product and customer service requests.</li>
            <li>Send you a newsletter.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">4. Disclosure of Your Information</h2>
          <p className="text-foreground">
            We may share information we have collected about you in certain situations. Your information may be disclosed as follows:
          </p>
          <ul className="list-disc list-inside pl-4 mt-2 space-y-1 text-foreground">
            <li>
              <strong>By Law or to Protect Rights:</strong> If we believe the release of information about you is necessary to respond to legal process, to investigate or remedy potential violations of our policies, or to protect the rights, property, and safety of others, we may share your information as permitted or required by any applicable law, rule, or regulation.
            </li>
            <li>
              <strong>Third-Party Service Providers:</strong> We may share your information with third parties that perform services for us or on our behalf, including payment processing, data analysis, email delivery, hosting services, customer service, and marketing assistance. This includes Google for AI model processing.
            </li>
            <li>
              <strong>Business Transfers:</strong> We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.
            </li>
          </ul>
        </section>

        <section>
            <h2 className="text-2xl font-semibold text-foreground mb-3">5. Third-Party Advertising & Ezoic</h2>
            <p className="text-foreground">
                We use third-party advertising companies to serve ads when you visit the Website. These companies may use information about your visits to this and other websites that are contained in web cookies in order to provide advertisements about goods and services of interest to you.
            </p>
            <p className="text-foreground mt-2">
                This site uses Ezoic's advertising services. Ezoic's privacy policy is in effect and can be reviewed <a href="http://g.ezoic.net/privacy/imagenbrainai.in" target="_blank" rel="noopener noreferrer" className="text-foreground hover:underline">here</a>. The required disclosures for our use of Ezoic's services are embedded below.
            </p>
            <div className="mt-4 p-4 border rounded-lg bg-muted/50">
                <span id="ezoic-privacy-policy-embed"></span>
            </div>
        </section>
        
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">6. Data Security</h2>
          <p className="text-foreground">
            We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.
          </p>
        </section>
        
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">7. Data Retention</h2>
          <p className="text-foreground">
            We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy policy, unless a longer retention period is required or permitted by law (such as tax, accounting or other legal requirements). For image generation history stored locally via browser storage, you have control over its deletion.
          </p>
        </section>
        
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">8. Your Rights</h2>
          <p className="text-foreground">
            Depending on your location, you may have certain rights regarding your personal information, such as the right to access, correct, or delete your data. To exercise these rights, please contact us.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">9. Policy for Children</h2>
          <p className="text-foreground">
            We do not knowingly solicit information from or market to children under the age of 13. If you become aware of any data we have collected from children under age 13, please contact us using the contact information provided below.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">10. Changes to This Privacy Policy</h2>
          <p className="text-foreground">
            We may update this privacy policy from time to time. The updated version will be indicated by an updated "Last Updated" date and the updated version will be effective as soon as it is accessible. We encourage you to review this privacy policy frequently to be informed of how we are protecting your information.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">11. Contact Us</h2>
          <p className="text-foreground">
            If you have questions or comments about this Privacy Policy, please contact us at:
            <br />
            Imagen BrainAi Team
            <br />
            Email: <a href="mailto:privacy@imagenbrain.ai" className="text-foreground hover:underline">privacy@imagenbrain.ai</a>
          </p>
        </section>
        <p className="font-bold mt-4 text-destructive text-center">
            Reminder: This content is for placeholder purposes only. Consult with a legal professional to create a compliant Privacy Policy.
        </p>
      </div>
    </main>
  );
}
