
import { ArticlesSection } from '@/components/vision-forge/ArticlesSection';
import { getArticles } from '@/lib/articles';
import type { Metadata } from 'next';
import { Suspense } from 'react';
import { ArticlesSkeleton } from '@/components/vision-forge/ArticlesSkeleton';

export const metadata: Metadata = {
    title: 'Tutorials | Imagen BrainAi',
    description: 'Learn how to create stunning AI art with our step-by-step tutorials, generated by Imagen BrainAi.',
};

const tutorialsTopics = [
    'How to Use AI to Create Professional Product Mockups',
    'From Concept to Reality: A Full AI Artwork Tutorial',
    'Fixing Mangled Hands and Faces in AI-Generated Images',
    'A Beginner\'s Guide to Inpainting and Outpainting with AI',
];

async function ArticleList() {
    const articles = await getArticles('Tutorials', tutorialsTopics);
    return <ArticlesSection articles={articles} topics={tutorialsTopics} category="Tutorials" />;
}

export default function TutorialsPage() {
    return (
        <main className="py-12">
            <section className="container mx-auto px-4">
                <header className="text-center mb-12">
                    <h2 className="text-4xl font-extrabold tracking-tight text-foreground">
                        AI Art Tutorials
                    </h2>
                    <p className="text-muted-foreground mt-2 max-w-3xl mx-auto">
                        Step-by-step guides to help you master AI image generation, from basics to advanced techniques.
                    </p>
                </header>
                <Suspense fallback={<ArticlesSkeleton />}>
                    <ArticleList />
                </Suspense>
            </section>
        </main>
    );
}
