
import { ArticlesSection } from '@/components/vision-forge/ArticlesSection';
import { getArticles } from '@/lib/articles';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Tutorials | Imagen BrainAi',
    description: 'Learn how to create stunning AI art with our step-by-step tutorials, generated by Imagen BrainAi.',
};

const tutorialsTopics = [
    'A Complete Beginner\'s Guide to Your First AI Image',
    'How to Create Stunningly Realistic AI Portraits in Minutes',
    'A Tutorial on Generating Epic AI Fantasy Landscape Art',
    'Fixing Common Problems like Hands and Faces in AI',
];

export default async function TutorialsPage() {
    const articles = await getArticles('Tutorials', tutorialsTopics);
    return (
        <main className="py-12">
            <ArticlesSection 
                articles={articles}
                topics={tutorialsTopics} 
                category="Tutorials" 
                headline="AI Art Tutorials"
                subheadline="Step-by-step guides to help you master AI image generation, from basics to advanced techniques."
            />
        </main>
    );
}
