
name: Regenerate Article Category Every 5 Minutes

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Article Regeneration
        run: |
          response=$(curl --request GET \
            --url 'https://vision-forge-ai-74a62.web.app/api/cron/regenerate-articles' \
            --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}' \
            --header 'Content-Type: application/json' \
            --fail)
          
          echo "API Response: $response"
        env:
          # The CRON_SECRET must be set in your project's repository secrets.
          # It should be a long, random string.
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
