
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer | Imagen BrainAi',
  description: 'Read the Disclaimer for Imagen BrainAi regarding the use of our AI image generation services and content.',
};

export default function DisclaimerPage() {
  return (
    <main className="container mx-auto py-12 px-4">
      <header className="text-center mb-10">
        <h1 className="text-4xl font-extrabold tracking-tight text-primary mb-3">
          Disclaimer
        </h1>
        <p className="text-lg text-muted-foreground">Last Updated: June 27, 2024</p>
      </header>

      <div className="max-w-3xl mx-auto space-y-6 text-foreground/80 text-base leading-relaxed">
        <p className="font-bold text-destructive">
            IMPORTANT: This is a template Disclaimer and should be reviewed and customized by a legal professional. Do not use this template as-is for your live website.
        </p>
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">1. General Information</h2>
          <p>
            The information provided by Imagen BrainAi ("we," "us," or "our") on imagenbrain.ai (the "Site") and our AI image generation service is for general informational and creative purposes only. All information on the Site and generated by the Service is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site or generated by the Service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">2. AI-Generated Content</h2>
          <p>
            The images generated by Imagen BrainAi are created by an artificial intelligence model (Google's Imagen 3). While we strive for high-quality and relevant outputs based on your prompts, AI-generated content can be unpredictable and may sometimes produce unexpected, inaccurate, or unintended results.
          </p>
          <p className="mt-2">
            We do not guarantee that the generated images will always be fit for a specific purpose, free from errors, or perfectly align with your expectations. Users are responsible for reviewing and verifying the suitability of any AI-generated content for their intended use.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">3. No Professional Advice</h2>
          <p>
            The information and content provided by Imagen BrainAi do not constitute professional advice (e.g., legal, financial, medical). Any reliance you place on such information is strictly at your own risk. You should consult with appropriate professionals before making decisions based on information or content obtained from our Service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">4. Use At Your Own Risk</h2>
          <p>
            Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the Site or our Service or reliance on any information provided on the Site or generated by our Service. Your use of the Site and our Service and your reliance on any information or generated content is solely at your own risk.
          </p>
        </section>
        
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">5. Content Ownership and Responsibility</h2>
          <p>
            Users are responsible for the prompts they provide and ensuring they have the right to use such prompts. Users are also responsible for how they use the images generated by the Service, including compliance with any applicable laws (e.g., copyright, trademark, privacy, decency). Imagen BrainAi does not claim ownership over the prompts you submit or the specific unique expressions in images generated based on those prompts, subject to our Terms of Service. However, Imagen BrainAi is not responsible for any misuse or infringement of third-party rights related to the content generated or used by users.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">6. External Links Disclaimer</h2>
          <p>
            The Site may contain (or you may be sent through the Site) links to other websites or content belonging to or originating from third parties or links to websites and features in banners or other advertising. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the site or any website or feature linked in any banner or other advertising.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">7. Errors and Omissions Disclaimer</h2>
          <p>
            While we strive to make the information on our Site and Service as accurate as possible, the Site and Service may contain errors or omissions. We are not responsible for any errors or omissions, or for the results obtained from the use of this information.
          </p>
        </section>
        
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">8. Fair Use Disclaimer</h2>
          <p>
            The Site may contain copyrighted material the use of which has not always been specifically authorized by the copyright owner. We are making such material available for criticism, comment, news reporting, teaching, scholarship, or research. We believe this constitutes a "fair use" of any such copyrighted material as provided for in section 107 of the US Copyright Law.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">9. Contact</h2>
          <p>
            If you have any feedback, comments, requests for technical support or other inquiries, please contact us by email: <a href="mailto:support@imagenbrain.ai" className="text-primary hover:underline">support@imagenbrain.ai</a>.
          </p>
        </section>
         <p className="font-bold mt-4 text-destructive text-center">
            Reminder: This content is for placeholder purposes only. Consult with a legal professional to create a compliant Disclaimer.
        </p>
      </div>
    </main>
  );
}
